services:
  mongodb:
    container_name: mongodb 
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  mongoexpress:
    container_name: mongoexpress
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin 
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_REQUEST_SIZE=999kb
      - ME_CONFIG_SITE_BASEURL=/


volumes:
  mongodb_data:
    driver: local 

  